server:
  port: 1400

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://34.126.137.107:5432/travelmarketplace
    username: postgres
    password: capstonevlu
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  application:
    name: manage-booking


eureka:
  instance:
    hostname: 34.126.186.221
  client:
    service-url:
      defaultZone: http://34.126.186.221:8761/eureka/

